"""empty message

Revision ID: 8544bc26c614
Revises: eeecf7bb394b
Create Date: 2019-12-31 00:24:51.984980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8544bc26c614'
down_revision = 'eeecf7bb394b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('gender', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=True))
    # ### end Alembic commands ###
